language: ruby
rvm:
- 2.1.1
script:
- RAILS_ENV=test bundle exec rake --trace db:create db:migrate
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: TmxIkGKxxhQoqdjvKIMAgejuzju89VTc1toB4Qk2xTdDvkNYQwEZ7VANmZJ5xybuS6wHCL1Zq+d10mhCwVBHYy00KY5n3X1dNDppVyvcSlndKqESPmnwEatIIMwlS/OrkSXPO+cUzAJeGYF3z1JqWP2n2eATHzUszVDHvBequ+M=
  app: fuck-it-bucket
  on:
    repo: simplyaubs/gratefulgarden
